version: '3'

volumes:
  pg_data:
    driver: local

services:
  postgres:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    restart: always
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app