version: '3'

volumes:
  pg_data:
    driver: local
  upload:
    driver: local

services:
  postgres:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbitmq:
    restart: always
    image: rabbitmq:latest

  app:
    restart: always
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
      - upload:/tmp

  worker:
    restart: always
    depends_on:
      - rabbitmq
    build:
      context: .
      dockerfile: DockerfileWorker
      args:
        - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
        - CELERY_BROKER_URL=${CELERY_BROKER_URL}
    volumes:
      - .:/app
      - upload:/tmp